kind: pipeline
name: default

steps:
- name: build
  image: rikorose/gcc-cmake 
  commands:
  - cmake ./
  - make
  
- name: test
  image: gcc
  commands:
  - make test

- name: gcc-build
  image: gcc
  commands:
    - g++ src/main.cpp
