version: 2.1

jobs:
  build:
    docker:
      - image: rikorose/gcc-cmake

    steps:
      - checkout
      - run: cmake ./
      - run: make

  check:
    docker:
      - image: neszt/cppcheck-docker

    steps:
      - checkout
      - run: cppcheck src
